[package]
name = "search_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
serde_json = "1.0.118"
tokio = { version = "*", features = ["full"] }
